/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.spark.shuffle.parquet.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroTestEntity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTestEntity\",\"namespace\":\"org.apache.spark.shuffle.parquet.avro\",\"fields\":[{\"name\":\"a\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"b\",\"type\":[\"null\",\"long\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String a;
  @Deprecated public java.lang.Long b;

  /**
   * Default constructor.
   */
  public AvroTestEntity() {}

  /**
   * All-args constructor.
   */
  public AvroTestEntity(java.lang.String a, java.lang.Long b) {
    this.a = a;
    this.b = b;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return a;
    case 1: return b;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: a = (java.lang.String)value$; break;
    case 1: b = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'a' field.
   */
  public java.lang.String getA() {
    return a;
  }

  /**
   * Sets the value of the 'a' field.
   * @param value the value to set.
   */
  public void setA(java.lang.String value) {
    this.a = value;
  }

  /**
   * Gets the value of the 'b' field.
   */
  public java.lang.Long getB() {
    return b;
  }

  /**
   * Sets the value of the 'b' field.
   * @param value the value to set.
   */
  public void setB(java.lang.Long value) {
    this.b = value;
  }

  /** Creates a new AvroTestEntity RecordBuilder */
  public static AvroTestEntity.Builder newBuilder() {
    return new AvroTestEntity.Builder();
  }
  
  /** Creates a new AvroTestEntity RecordBuilder by copying an existing Builder */
  public static AvroTestEntity.Builder newBuilder(AvroTestEntity.Builder other) {
    return new AvroTestEntity.Builder(other);
  }
  
  /** Creates a new AvroTestEntity RecordBuilder by copying an existing AvroTestEntity instance */
  public static AvroTestEntity.Builder newBuilder(AvroTestEntity other) {
    return new AvroTestEntity.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroTestEntity instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroTestEntity>
    implements org.apache.avro.data.RecordBuilder<AvroTestEntity> {

    private java.lang.String a;
    private java.lang.Long b;

    /** Creates a new Builder */
    private Builder() {
      super(AvroTestEntity.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(AvroTestEntity.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing AvroTestEntity instance */
    private Builder(AvroTestEntity other) {
            super(AvroTestEntity.SCHEMA$);
      if (isValidValue(fields()[0], other.a)) {
        this.a = data().deepCopy(fields()[0].schema(), other.a);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.b)) {
        this.b = data().deepCopy(fields()[1].schema(), other.b);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'a' field */
    public java.lang.String getA() {
      return a;
    }
    
    /** Sets the value of the 'a' field */
    public AvroTestEntity.Builder setA(java.lang.String value) {
      validate(fields()[0], value);
      this.a = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'a' field has been set */
    public boolean hasA() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'a' field */
    public AvroTestEntity.Builder clearA() {
      a = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'b' field */
    public java.lang.Long getB() {
      return b;
    }
    
    /** Sets the value of the 'b' field */
    public AvroTestEntity.Builder setB(java.lang.Long value) {
      validate(fields()[1], value);
      this.b = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'b' field has been set */
    public boolean hasB() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'b' field */
    public AvroTestEntity.Builder clearB() {
      b = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroTestEntity build() {
      try {
        AvroTestEntity record = new AvroTestEntity();
        record.a = fieldSetFlags()[0] ? this.a : (java.lang.String) defaultValue(fields()[0]);
        record.b = fieldSetFlags()[1] ? this.b : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
